name: Auto Green

on:
  schedule:
    - cron: '0 0 * * *' # Chạy tự động vào 00:00 mỗi ngày
  workflow_dispatch: # Cho phép bạn bấm nút chạy thử thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update last updated date
        run: |
          echo "Last updated on: $(date)" > activity.txt

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add activity.txt
          git commit -m "Auto update activity log"
          git push
